---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: eagle-{{replica}}
    app.kubernetes.io/component: exporter
  name: eagle-{{replica}}
  # namespace: eagle
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: eagle-{{replica}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: eagle-{{replica}}
    app.kubernetes.io/component: exporter
  name: eagle-{{replica}}
  # namespace: eagle
spec:
  endpoints:
  - port: metrics
    interval: 5s
  selector:
    matchLabels:
      app.kubernetes.io/name: eagle-{{replica}}
      app.kubernetes.io/component: exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: eagle-{{replica}}
    app.kubernetes.io/component: exporter
  name: eagle-{{replica}}
  # namespace: eagle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eagle-{{replica}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eagle-{{replica}}
    spec:
      containers:
      - image: quay.io/paulfantom/eagle:master
        imagePullPolicy: Always
        name: eagle
        args:
        - --tempo=10
        ports:
          - containerPort: 8080
            name: metrics
      restartPolicy: Always
